# Generated by Django 6.0.2 on 2026-02-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
