# Generated by Django 6.0.2 on 2026-02-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_jobrole_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='display_hours',
        ),
        migrations.AddField(
            model_name='announcement',
            name='display_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hrprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hr_photos/'),
        ),
    ]
